.TH FIZMO-CONSOLE-LAUNCHER 6 "September 11, 2017" "0.7.13"
.SH NAME
fizmo-console-launcher
- helper script for launching fizmo-console as zcode-interpreter.

.SH SYNOPSIS
.B fizmo-console-launcher
[ options ]

.SH DESCRIPTION
In the context of the debian alternatives, fizmo-console is to be supposed to
be launched as "zcode-interpreter", which is what this script does. In case it
is run in a terminal fizmo-console is invoked directly, else it is started
inside a x-terminal-emulator.

.SH OPTIONS
All otions are passed directly to fizmo-console.

.SH SEE ALSO
.BR fizmo-ncursesw-launcher(6),
.BR fizmo-ncursesw-sdl2(6)

.SH AUTHOR
This script was written by Stephen Kitt in the context of debian
issue #812412.

